# Generated by Django 4.1 on 2022-08-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_name", models.CharField(max_length=100)),
                ("usuario_email", models.CharField(max_length=50)),
                ("usuario_type", models.CharField(max_length=1)),
                ("usuario_password", models.CharField(max_length=8)),
            ],
        ),
    ]
