# Generated by Django 4.1 on 2022-09-19 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("freework", "0003_alter_aspirante_id_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        choices=[
                            ("Aspirante", "Aspirante"),
                            ("Reclutador", "Reclutador"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("celular", models.CharField(max_length=255)),
                (
                    "intereses",
                    models.CharField(
                        choices=[
                            ("Humanidades", "Humanidades"),
                            ("Ciencias exactas", "Ciencias exactas"),
                            ("Ciencias naturales", "Ciencias naturales"),
                            ("Ciencias sociales", "Ciencias sociales"),
                            ("Ciencias de la salud", "Ciencias de la salud"),
                            ("Negocios", "Negocios"),
                            ("Leyes", "Leyes"),
                            ("Tecnología", "Tecnologia"),
                        ],
                        default="8",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Usuario",),
        migrations.RemoveField(model_name="aspirante", name="id_user",),
        migrations.AddField(
            model_name="aspirante",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
