# Generated by Django 4.1 on 2022-09-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freework", "0004_perfil_delete_usuario_remove_aspirante_id_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="perfil", name="celular",),
    ]
