# Generated by Django 4.1 on 2022-09-23 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("freework", "0006_aspiranteinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=255, null=True)),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("Humanidades", "Humanidades"),
                            ("Ciencias exactas", "Ciencias exactas"),
                            ("Ciencias naturales", "Ciencias naturales"),
                            ("Ciencias sociales", "Ciencias sociales"),
                            ("Ciencias de la salud", "Ciencias de la salud"),
                            ("Negocios", "Negocios"),
                            ("Leyes", "Leyes"),
                            ("Tecnología", "Tecnologia"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("lastjob", models.CharField(max_length=255, null=True)),
                ("desclastjob", models.CharField(max_length=255, null=True)),
                (
                    "phone",
                    models.PositiveIntegerField(blank=True, max_length=10, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("Aspirante", "Aspirante"),
                            ("Reclutador", "Reclutador"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255, null=True)),
                (
                    "phone",
                    models.PositiveIntegerField(blank=True, max_length=10, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="aspiranteinfo", name="user",),
        migrations.RemoveField(model_name="perfil", name="user",),
        migrations.RemoveField(model_name="reclutador", name="id_user",),
        migrations.DeleteModel(name="Aspirante",),
        migrations.DeleteModel(name="AspiranteInfo",),
        migrations.DeleteModel(name="Perfil",),
        migrations.DeleteModel(name="Reclutador",),
    ]
