# Generated by Django 4.1 on 2022-10-06 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("freework", "0008_alter_applicant_interest_alter_applicant_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradeapplicant",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
