# Generated by Django 4.1 on 2022-10-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("freework", "0010_remove_gradeapplicant_average_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicant", name="soft_skills",),
        migrations.AddField(
            model_name="gradeapplicant",
            name="applicant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="freework.applicant",
            ),
        ),
    ]
