# Generated by Django 4.1 on 2022-10-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freework", "0012_allapplicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradeapplicant",
            name="comment",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gradeapplicant",
            name="comment_sr",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
