# Generated by Django 4.1 on 2022-10-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freework", "0014_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentiment",
            name="analyze_save",
            field=models.CharField(default="Positive", max_length=255),
        ),
    ]
