# Generated by Django 4.1 on 2022-10-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freework", "0016_remove_sentiment_text_analyzed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gradeapplicant", old_name="comment", new_name="comment_save",
        ),
        migrations.RenameField(
            model_name="gradeapplicant",
            old_name="comment_sr",
            new_name="comment_to_analyze",
        ),
    ]
