# Generated by Django 4.1 on 2022-10-17 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freework", "0018_gradeapplicant_sentiment_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="gradeapplicant", name="comment_save",),
        migrations.RemoveField(model_name="gradeapplicant", name="comment_to_analyze",),
    ]
