# Generated by Django 4.1 on 2022-11-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freework", "0020_gradeapplicant_random_morejobs_emailuser2_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="gradeapplicant", name="applicant",),
        migrations.RemoveField(model_name="gradeapplicant", name="code",),
        migrations.RemoveField(model_name="gradeapplicant", name="random",),
    ]
